name: Release

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "🚀 pretending to build"
        run: echo "Hello!!! The Pretend Build is done"

  deploy-to-staging:
    environment:
      name: staging
    name: Staging
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: "🚀🚀 pretending to release"
        run: echo "Hello!!! The Pretend Release to Staging is done"


  deploy-to-production:
    environment:
      name: production
    name: Production
    runs-on: ubuntu-latest
    needs:
      - deploy-to-staging
    steps:
      - name: "🚀🚀🚀 pretending to release"
        run: echo "Hello!!! The Pretend Release to Production is done"
